server:
  port: 1111

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_absent
  application:
    name: server-galaxy
  jpa:
    hibernate:
      ddl-auto: none

#MyBatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.galaxy.model

#endpoints 配置
management:
  server:
    port: 8090
    servlet:
      context-path: /monitor
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

logging:
  config: classpath:log4j2.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:2222/eureka/