mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.galaxy.bigdata.hbase.model
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:phoenix:quickstart.cloudera:2181
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      maximum-pool-size: 20
      minimum-idle: 2
      validation-timeout: 300000
      idle-timeout: 600000
      connection-test-query: select 1+1