version: '2.2'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile
    image: holaweb
    ports:
      - 8085:8085
    networks:
      - network1
    scale: 1

networks:
  network1: