rbac:
  init:
    attributeType:
      - id: 1
        name: report
      - id: 2
        name: alert
      - id: 3
        name: dashboard
      - id: 4
        name: topology

    resourceTypes:
      - id: 1
        name: root
        tree: true
        description: 根节点

      - id: 2
        name: menu
        tree: true
        description: 菜单

      - id: 3
        name: dataSource
        tree: true
        description: 数据源

      - id: 4
        name: func
        tree: true
        description: 功能

    resources:

      #菜单类型资源
      #根节点
      - id: 1
        name: 根节点
        resourceType.id: 1
        uri: root
        parentId: null
        description: 根节点

      - id: 2
        name: 数据分析
        resourceType.id: 2
        uri: /data
        parentId: 1
        description: 数据分析

      - id: 3
        name: 系统管理
        resourceType.id: 2
        uri: /sys
        parentId: 1
        description: 系统管理

      - id: 4
        name: 调度管理
        resourceType.id: 2
        uri: /scheduler
        parentId: 1
        description: 调度管理

      #数据分析
      - id: 10
        name: 日志分析
        resourceType.id: 2
        uri: /analyse/log/*
        parentId: 2
        description: 日志分析

      - id: 11
        name: 仪表板
        resourceType.id: 2
        uri: /meta/dashboard/*
        parentId: 2
        description: 仪表板

      - id: 12
        name: 告警配置
        resourceType.id: 2
        uri: /meta/alert/*
        parentId: 2
        description: 告警配置

      - id: 13
        name: 数据沙盘
        resourceType.id: 2
        uri: /meta/topology/*
        parentId: 2
        description: 数据沙盘

      - id: 14
        name: 定时报告
        resourceType.id: 2
        uri: /meta/report/*
        parentId: 2
        description: 定时报告

      - id: 15
        name: 定时报告下载
        resourceType.id: 4
        uri: /node/download/*
        parentId: 14
        description: 定时报告下载

      - id: 16
        name: 历史报告查询
        resourceType.id: 4
        uri: /node/report/*
        parentId: 14
        description: 历史报告查询

      - id: 18
        name: 仪表板导出
        resourceType.id: 4
        uri: /meta/file/exportDashboardConfigByID
        parentId: 11
        description: 仪表板导出

      - id: 19
        name: 仪表板导入
        resourceType.id: 4
        uri: /meta/file/importDashboardConfigByUID
        parentId: 11
        description: 仪表板导入

      #系统管理
      - id: 100
        name: 用户管理
        resourceType.id: 2
        uri: /rbac/user/*
        parentId: 3
        description: 用户管理

      - id: 101
        name: 角色管理
        resourceType.id: 2
        uri: /rbac/role/*
        parentId: 3
        description: 角色管理

      - id: 103
        name: 用户组管理
        resourceType.id: 2
        uri: /rbac/group/*
        parentId: 3
        description: 用户组管理

      - id: 104
        name: 资源管理
        resourceType.id: 2
        uri: /rbac/resource/*
        parentId: 3
        description: 资源管理

      - id: 105
        name: 数据源管理
        resourceType.id: 2
        uri: /api/ds/*
        parentId: 3
        description: 数据源管理

      - id: 106
        name: 代理服务器
        resourceType.id: 2
        uri: /collectd/nodes/*
        parentId: 3
        description: 代理服务器

      - id: 107
        name: 数据字典
        resourceType.id: 2
        uri: /meta/datadictionary/*
        parentId: 3
        description: 数据字典

      - id: 108
        name: 系统设置
        resourceType.id: 2
        uri: /meta/systemConfig/*
        parentId: 3
        description: 系统设置

      - id: 109
        name: 数据流管理
        resourceType.id: 4
        uri: /collectd/flows/*
        parentId: 105
        description: 数据流管理

      - id: 110
        name: 解析规则管理
        resourceType.id: 4
        uri: /collectd/rules/*
        parentId: 105
        description: 解析规则管理

      - id: 111
        name: 数据源元数据管理
        resourceType.id: 4
        uri: /collectd/sources/*
        parentId: 105
        description:  数据源元数据管理

      - id: 112
        name:  关键词脱敏管理
        resourceType.id: 4
        uri: /meta/sensitiveWord/*
        parentId: 108
        description:  关键词脱敏管理

      - id: 113
        name:  脱敏字段管理
        resourceType.id: 4
        uri: /meta/sensitiveWordFilter/*
        parentId: 108
        description:  脱敏字段管理

      - id: 114
        name:  邮件配置管理
        resourceType.id: 4
        uri: /scheduler/email/*
        parentId: 108
        description:  邮件配置管理

      # 调度管理
      - id: 200
        name: 任务管理
        resourceType.id: 2
        uri: /scheduler/job/*
        parentId: 4
        description: 任务管理

      - id: 201
        name: 调度日志
        resourceType.id: 2
        uri: /scheduler/log/*
        parentId: 4
        description: 调度日志

      - id: 202
        name: 执行器管理
        resourceType.id: 2
        uri: /scheduler/group/*
        parentId: 4
        description: 执行器管理


      #数据源类型资源

      - id: 300
        name: .dip
        resourceType.id: 3
        uri: .dip
        parentId: 1
        description: .dip

      - id: 301
        name: .alert
        resourceType.id: 3
        uri: .alert
        parentId: 1
        description: .alert

      - id: 302
        name: .es_cluster
        resourceType.id: 3
        uri: .es_cluster
        parentId: 1
        description: .es_cluster

      - id: 303
        name: .es_node
        resourceType.id: 3
        uri: .es_node
        parentId: 1
        description: .es_node

      - id: 304
        name: .es_source
        resourceType.id: 3
        uri: .es_source
        parentId: 1
        description: .es_source


    groups:
      - id: 1
        groupName: 默认分组
        description: 默认分组

    roles:
      - id: 1
        roleName: 超级管理员
        description: 超级管理员

      - id: 2
        roleName: 管理员
        description: 管理员

      - id: 3
        roleName: 默认角色
        description: 默认角色

    privileges:
      #超级管理员角色权限
      - roleId: 1
        resource.id: 2
      - roleId: 1
        resource.id: 3
      - roleId: 1
        resource.id: 4
      - roleId: 1
        resource.id: 10
      - roleId: 1
        resource.id: 11
      - roleId: 1
        resource.id: 12
      - roleId: 1
        resource.id: 13
      - roleId: 1
        resource.id: 14
      - roleId: 1
        resource.id: 15
      - roleId: 1
        resource.id: 16
      - roleId: 1
        resource.id: 18
      - roleId: 1
        resource.id: 19
      - roleId: 1
        resource.id: 100
      - roleId: 1
        resource.id: 101
      - roleId: 1
        resource.id: 103
      - roleId: 1
        resource.id: 104
      - roleId: 1
        resource.id: 105
      - roleId: 1
        resource.id: 106
      - roleId: 1
        resource.id: 107
      - roleId: 1
        resource.id: 108
      - roleId: 1
        resource.id: 109
      - roleId: 1
        resource.id: 110
      - roleId: 1
        resource.id: 111
      - roleId: 1
        resource.id: 112
      - roleId: 1
        resource.id: 113
      - roleId: 1
        resource.id: 114
      - roleId: 1
        resource.id: 200
      - roleId: 1
        resource.id: 201
      - roleId: 1
        resource.id: 202
      - roleId: 1
        resource.id: 300
      - roleId: 1
        resource.id: 301
      - roleId: 1
        resource.id: 302
      - roleId: 1
        resource.id: 303
      - roleId: 1
        resource.id: 304
      #管理员角色权限
      - roleId: 2
        resource.id: 2
      - roleId: 2
        resource.id: 3
      - roleId: 2
        resource.id: 4
      - roleId: 2
        resource.id: 10
      - roleId: 2
        resource.id: 11
      - roleId: 2
        resource.id: 12
      - roleId: 2
        resource.id: 13
      - roleId: 2
        resource.id: 14
      - roleId: 2
        resource.id: 15
      - roleId: 2
        resource.id: 16
      - roleId: 2
        resource.id: 18
      - roleId: 2
        resource.id: 19
      - roleId: 2
        resource.id: 100
      - roleId: 2
        resource.id: 101
      - roleId: 2
        resource.id: 103
      - roleId: 2
        resource.id: 105
      - roleId: 2
        resource.id: 106
      - roleId: 2
        resource.id: 107
      - roleId: 2
        resource.id: 108
      - roleId: 2
        resource.id: 109
      - roleId: 2
        resource.id: 110
      - roleId: 2
        resource.id: 111
      - roleId: 2
        resource.id: 112
      - roleId: 2
        resource.id: 113
      - roleId: 2
        resource.id: 114
      - roleId: 2
        resource.id: 200
      - roleId: 2
        resource.id: 201
      - roleId: 2
        resource.id: 202
      - roleId: 2
        resource.id: 300
      - roleId: 2
        resource.id: 301
      - roleId: 2
        resource.id: 302
      - roleId: 2
        resource.id: 303
      - roleId: 2
        resource.id: 304

      #默认角色权限
      - roleId: 3
        resource.id: 2
      - roleId: 3
        resource.id: 10
      - roleId: 3
        resource.id: 11
      - roleId: 3
        resource.id: 12
      - roleId: 3
        resource.id: 13
      - roleId: 3
        resource.id: 14
      - roleId: 3
        resource.id: 15
      - roleId: 3
        resource.id: 16
      - roleId: 3
        resource.id: 18
      - roleId: 3
        resource.id: 19

    users:
      - id: 1
        mail: root@aoneai.com
        password: 63a9f0ea7bb98050796b649e85481845 #root
        name: root
      - id: 2
        mail: admin@aoneai.com
        password: 21232f297a57a5a743894a0e4a801fc3 #admin
        name: admin
      - id: 3
        mail: test@aoneai.com
        password: 098f6bcd4621d373cade4e832627b4f6 #test
        name: test

    userRoles:
      - userId: 1
        roleId: 1
      - userId: 2
        roleId: 2
      - userId: 3
        roleId: 3

    userGroups:
      - groupId: 1
        userId: 1
      - groupId: 1
        userId: 2