package com.galaxy.web.jpa;

import com.galaxy.dao.jpa.CityRepository;
import com.galaxy.domain.ReturnT;
import com.galaxy.entity.City;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * Created by wangpeng on 14/03/2018.
 */
@Controller
@RequestMapping("/jpa/city")
public class CityController {

    //This means to get the bean called userRepository. Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CityRepository cityRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    ReturnT<String> addNewUser(@RequestBody City city) {
        this.cityRepository.save(city);
        return new ReturnT<String>();
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<City> getAllCities() {
        // This returns a JSON or XML with the users
        return this.cityRepository.findAll();
    }
}
