spring:
  application:
    name: dubbo-consumer
server:
  port: 6012

#指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20880

  #指定注册中心的位置
  registry:
    address: zookeeper://localhost:2181

  #统一设置服务提供方的规则
  consumer:
    timeout: 5000